CREATE DATABASE COUNT_SALARY_CATEGORIES;

USE COUNT_SALARY_CATEGORIES

CREATE TABLE Accounts (
    account_id INT PRIMARY KEY,
    income INT
);

INSERT INTO Accounts (account_id, income)
VALUES 
(3, 108939),
(2, 12747),
(8, 87709),
(6, 91796);

SELECT * FROM Accounts;

WITH FINAL AS (
SELECT CASE WHEN INCOME<20000 THEN 'Low Salary' WHEN INCOME BETWEEN 20000 AND 50000 
THEN 'Average Salary' WHEN 
INCOME>50000 THEN 'High Salary' END AS CATEGORY FROM ACCOUNTS
)
SELECT CATEGORY, COUNT(*) AS ACCOUNTS_COUNT FROM FINAL GROUP BY CATEGORY;

-- AND

SELECT 'Low Salary' AS CATEGORY, COUNT(*) AS accounts_count  FROM ACCOUNTS WHERE INCOME<20000
UNION ALL
SELECT 'Average Salary' AS CATEGORY, COUNT(*) AS accounts_count  FROM ACCOUNTS 
WHERE INCOME BETWEEN 20000 AND 50000
UNION ALL
SELECT 'High Salary' AS CATEGORY, COUNT(*) AS accounts_count  FROM ACCOUNTS WHERE INCOME>50000

