CREATE DATABASE LAST_PERSON_FIT_IN_BUS;

USE LAST_PERSON_FIT_IN_BUS;

CREATE TABLE Queue (
    person_id INT PRIMARY KEY,
    person_name VARCHAR(100),
    weight INT,
    turn INT
);

INSERT INTO Queue (person_id, person_name, weight, turn)
VALUES 
(5, 'Alice', 250, 1),
(4, 'Bob', 175, 5),
(3, 'Alex', 350, 2),
(6, 'John Cena', 400, 3),
(1, 'Winston', 500, 6),
(2, 'Marie', 200, 4);

SELECT * FROM QUEUE ORDER BY TURN ASC;


WITH FINAL AS (
SELECT PERSON_ID, PERSON_NAME, WEIGHT, TURN, SUM(WEIGHT) OVER (ORDER BY TURN) AS
TOTAL_WEIGHT FROM QUEUE
)
SELECT TOP 1 PERSON_NAME FROM FINAL WHERE TOTAL_WEIGHT<=1000 ORDER BY TOTAL_WEIGHT DESC;
