CREATE DATABASE MANAGER_LEFT_COMPANY;

USE MANAGER_LEFT_COMPANY;

CREATE TABLE EMPLOYEES (EMPLOYEE_ID INT, NAME VARCHAR(255), MANAGER_ID INT, SALARY INT);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, NAME, MANAGER_ID, SALARY) VALUES 
(3, 'Mila', 9, 60301),
(12, 'Antonella', NULL, 31000),
(13, 'Emery', NULL, 67084),
(1, 'Kalel', 11, 21241),
(9, 'Mikaela', NULL, 50937),
(11, 'Joziah', 6, 28485);

SELECT * FROM EMPLOYEES;

SELECT employee_id
FROM Employees as a
WHERE manager_id not in (SELECT employee_id FROM employees) and salary < 30000
ORDER BY employee_id ASC
